

### Get a specific person details passing nic
GET http://localhost:9090/identity/verify-nic/34e

### Post a specific person nic
POST http://localhost:9090/identity/verify-nic
content-type: application/json

{
    "nic":"34e"
}

###
POST http://localhost:9090/identity/users
content-type: application/json

{
    "birthDate": {
        "year": 1987,
        "month": 02,
        "day": 06
    },
    "name": "Rimas",
    "mobileNumber": "+94718923456"
}